### ISSUE TITLE
Strapi limitation on nested group data

### ISSUE THREAD

**Issue by rennemannd** [STEM-C/STEM-C#16]
There seems to be an issue in strapi where nested group data (such as an array) does not render correctly and will always appear null. Testing locally showed this was always true regardless of other factors (link type, data type, data requirements). 

This issue was discussed with a working solution [here](https://spectrum.chat/strapi/general/group-doesnt-appear-on-findall-with-relations~c0bcc957-3170-4e80-96de-ee3e7625b5bf). 

This either needs to be fixed or the entity model needs to be adjusted to account for this. Due to time restraints there will be a temporary fix setting blocks to be a 1st level array. This temporary change will be reflected in the schema as well as code in the workspace render.

- [x] Implement a fix that allows nested group data to appear in strapi
- [x] Adjust the frontend workspace render method to account for the corrected schema

**Comment by cgardnermccune** [comment]
We need to discuss the implications of this bug and the temporary fix in an upcoming meeting.

**Comment by nionata** [comment]
Closed in #47
