### ISSUE TITLE
React builds but is not usable 

### ISSUE THREAD

**Issue by rennemannd** [STEM-C/STEM-C#18]
The react fronted builds correctly but when index.html is accessed will error out with the following message: 
![avrgirl-bug](https://user-images.githubusercontent.com/11527230/81816176-f6b3cc00-94f8-11ea-8106-d7f2c15c6d36.PNG)

This is (likely) caused by the following code: 
![image](https://user-images.githubusercontent.com/11527230/81816264-177c2180-94f9-11ea-8d94-56933d89f2ac.png)

**Comment by nionata** [comment]
A possible resolution could be using the actual npm [module](https://github.com/noopkat/avrgirl-arduino). This may require use using a file, so we could modify the compile server to return a .hex file.

**Comment by rennemannd** [comment]
This was solved in #3
