### ISSUE TITLE
Client scaffold

### ISSUE THREAD

**Issue by nionata** [STEM-C/STEM-C#3]
- [x] Init a react app in the client scaffold
- [x] Add blockly
- [x] Serial api
- [x] Integrate with backend via REST calls to access activity list. 
- [x] Integrate with backend via REST calls to customize workspace. 
- [x] Finalize Client documentation BEFORE making a PR
- [x] Setup frontend middleware to properly serve react + routing
- [x] Configure build to handle new serving

**Comment by rennemannd** [comment]
Client conversion to react is mostly finished there is just some cleanup that remains. I'll make a PR into develop once it gets cleaned up.

**Comment by rennemannd** [comment]
This issue is finished but has a bug that prevents the merge, detailed [here](https://github.com/STEM-C/STEM-C/issues/18). BLOCKED until bug is fixed.

**Comment by nionata** [comment]
closed in #28
