### ISSUE TITLE
Authentication: Login View

### ISSUE THREAD

**Issue by rennemannd** [STEM-C/STEM-C#34]
This feature is based upon the following layout of views, this feature only requires that the numbered views be completed:

![view_model_num](https://user-images.githubusercontent.com/11527230/82929923-7eb2c080-9f52-11ea-8872-e8d9ea483a40.png)

1. This is the basic login view. This should allow a teacher to login on one screen and then view a basic dashboard of activities in the next screen.

- [x] Teacher/Mentor can view page to login
- [x] Teacher/Mentor route is protected 
- [x] Teacher/Mentor can view basic dashboard of topics/activities
- [x] Teacher/Mentor can view students in a given session
- [x] Teacher/Mentor can enable or disable sessions
- [x] Components are restyled using new antd standard.

**Comment by nionata** [comment]
https://docs.google.com/document/d/1btYZBzQF2O0xOaucXpkzlJwHRyt6Yc2sOiubBqAkc_8/edit?usp=sharing

**Comment by rennemannd** [comment]
Added @tamargoadam to issue to work on antd styling changes and added a few more technical requirements.

**Comment by rennemannd** [comment]
Not all requirements were met, however most were and this issue will be closed on next PR into develop. A new issue will be made using updated requirements from the previous meetings.
